### ISSUE TITLE
Install cleanup

### ISSUE THREAD

**Issue by daretodave** [mterm-io/mterm#32]
Because `mterm` needs `ts-loader` as it compiles user scripts, we need to isolate dep tree and cleanup `electron-builder.yaml`

Right now here's the `electron-builder.yaml` inclusion -

```yaml
extraFiles:
  - from: "./node_modules"
    to: "node_modules"
```

This needs to be -
```yaml
extraFiles:
  - from: "./node_modules/ts-loader"
    to: "node_modules/ts-loader"
```

But this wont just work. it needs to be done for `ts-loader` and all associated modules (e.g `chalk` etc). Crawling this dep tree will take some time and trial and error. A developer must:
- Add the next package (e.g `ts-loader` in this case)
- Run a build for a platform (e.g `npm run build:win`)
- Run the installer (e.g `dist/mterm___install.exe`)
- See the next dep error
- Add 
```yaml
extraFiles:
  - from: "./node_modules/ts-loader"
    to: "node_modules/ts-loader"
  - from: "./node_modules/chalk"
    to: "node_modules/chalk"
```

This will decrease our install package by a ton. Right now it's ~200mb for all the node modules. (which it should be around 80 tops)
